#!/bin/sh

log_info () {
  printf " \033[1;33mℹ\033[0m $1\n"
}

log_success () {
  printf " \033[00;32m✓\033[0m $1\n"
}

log_warning () {
  echo "⚠ - $@"
}


is_homebrew_installed () {
  if test ! $(which brew); then return 0; else return 1; fi
}

homebrew_not_installed_message () {
  log_warning "You should probably install Homebrew first\n https://github.com/mxcl/homebrew/wiki/installation"
}

brew_is_installed () {
  local s=`brew info $@ | head -3 | tail -1`
  if [ "$s" == "Not installed" ]; then return 1; else return 0; fi
}

brew_cask_is_installed () {
  local s=`brew cask info $@ | head -3 | tail -1`
  if [ "$s" == "Not installed" ]; then return 1; else return 0; fi
}

brew_install () {
  if brew_is_installed $@; then
    log_success "$@ is already installed"
  else
    brew install $@
  fi
}

brew_cask_install () {
  if brew_cask_is_installed $@; then
    log_success "$@ is already installed"
  else
    brew cask install $@
  fi
}


ensure_homebrew_install () {
  if [ ! is_homebrew_installed ]; then
    homebrew_not_installed_message
    exit 1
  fi

  return 0
}

