#!/bin/sh

COLOR_NONE="\033[0m"
COLOR_WHITE="\033[1;37m"
COLOR_BLACK="[0;30m"
COLOR_BLUE="\033[0;34m"
COLOR_BLUE_LIGHT="\033[1;34m"
COLOR_GREEN="\033[0;32m"
COLOR_GREEN_LIGHT="\033[1;32m"
COLOR_CYAN="\033[0;36m"
COLOR_CYAN_LIGHT="\033[1;36m"
COLOR_RED="\033[0;31m"
COLOR_RED_LIGHT="\033[1;31m"
COLOR_PURPLE="\033[0;35m"
COLOR_PURPLE_LIGHT="\033[1;35m"
COLOR_YELLOW="\033[0;33m"
COLOR_YELLOW_LIGHT="\033[1;33m"
COLOR_GRAY="\033[1;30m"
COLOR_GRAY_LIGHT="\033[0;37m"

log_info () {
  printf " ${COLOR_YELLOW_LIGHT}ℹ${COLOR_NONE} $1\n"
}

log_success () {
  printf " ${COLOR_GREEN_LIGHT}✓${COLOR_NONE} $1\n"
}

log_warning () {
  printf " ${COLOR_RED_LIGHT}⚠${COLOR_NONE} $1\n"
}

log_user () {
  printf " ${COLOR_PURPLE_LIGHT}☝${COLOR_NONE} $1\n"
}

is_homebrew_installed () {
  if test ! $(which brew); then return 0; else return 1; fi
}

homebrew_not_installed_message () {
  log_warning "You should probably install Homebrew first\n  https://github.com/mxcl/homebrew/wiki/installation"
}

brew_is_installed () {
  local s=`brew info $@ | head -3 | tail -1`
  if [ "$s" == "Not installed" ]; then return 1; else return 0; fi
}

brew_cask_is_installed () {
  local s=`brew cask info $@ | head -3 | tail -1`
  if [ "$s" == "Not installed" ]; then return 1; else return 0; fi
}

brew_install () {
  if brew_is_installed $@; then
    log_success "${COLOR_WHITE}${@} ${COLOR_NONE}is already installed"
  else
    brew install $@
  fi
}

brew_cask_install () {
  if brew_cask_is_installed $@; then
    log_success "${COLOR_WHITE}${@} ${COLOR_NONE}is already installed"
  else
    brew cask install $@
  fi
}


ensure_homebrew_install () {
  if [ ! is_homebrew_installed ]; then
    homebrew_not_installed_message
    exit 1
  fi

  return 0
}

