#!/bin/bash

alias g='git'

alias c='clear'
alias ll='ls -lha'

alias zshrc='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'
alias gitconfig='vim ~/.gitconfig'

alias tu='top -o cpu'
alias tm='top -o vsize'

alias update-vim-plugins='vim +BundleUpdate +qall'

# set wifi on/off
alias wifi='networksetup -setairportpower en0 on'
alias wifioff='networksetup -setairportpower en0 off'

alias grep='grep --color=auto'
alias so='source ~/.zshrc'
alias add-alias='vim ~/Dropbox/.dotfiles/zsh/aliases'

# List paths in a readable format
alias paths='echo $PATH | tr ":" "\n"'

# Start a webserver in current direcory on port 8888
alias simple-server='python -m SimpleHTTPServer 8888'

alias color=cdl

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done

