#!/bin/bash

alias g='git'

alias m='tmuxinator start'

alias c='clear'
alias ll='ls -lhA'

alias zshrc='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'

alias tu='top -o cpu'
alias tm='top -o vsize'

alias update-vim-plugins='vim +BundleUpdate +qall'

# set wifi on/off
alias wifi='networksetup -setairportpower en0 on'
alias wifioff='networksetup -setairportpower en0 off'

alias so='source ~/.zshrc'
alias add-alias='vim ~/.zsh/aliases'

# List paths in a readable format
alias paths='echo $PATH | tr ":" "\n"'

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done

# alias hub to git
if [ -x "$(which hub)" ]; then; eval "$(hub alias -s)"; fi
