#!/bin/bash

alias g='git'
alias m='tmuxinator start'
alias s='pmset sleepnow'
alias k='clear'
alias c='pygmentize -O style=monokai -f console256 -g'

alias ll='ls -lhA'

alias zshrc='vim ~/.zshrc'
alias vimrc='vim ~/.vimrc'

alias tu='top -o cpu'
alias tm='top -o vsize'

alias update-vim-plugins='vim +BundleUpdate +qall'

# set wifi on/off
alias wifi='networksetup -setairportpower en0 on'
alias wifioff='networksetup -setairportpower en0 off'

alias so='source ~/.zshrc'
alias add-alias='vim ~/.zsh/aliases'

# List paths in a readable format
alias paths='echo $PATH | tr ":" "\n"'

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "$method"="lwp-request -m '$method'"
done

# MAC manipulators
alias random-mac='sudo ifconfig en0 ether `openssl rand -hex 6 | sed "s/\(..\)/\1:/g; s/.$//"`'
alias restore-mac='sudo ifconfig en0 ether $MAC_ADDRESS'

alias speed-test='wget -O /dev/null http://speedtest.wdc01.softlayer.com/downloads/test10.zip'

# alias hub to git
if [ -x "$(which hub)" ]; then eval "$(hub alias -s)"; fi
