#!/bin/bash
# vi: sw=8:ts=8:noet

# open local host with specific port, default to 3000
olh() {
	local port=${1:-3000}
	open -a "Google Chrome Canary" http://localhost:$port;
}

doc() {
	open dash://"$@"
}

reload-canary() {
	osascript <<-EOF >/dev/null
	tell application "Google Chrome Canary"
		reload active tab of window 1
	end tell
	EOF
}

update-prezto() {
	cd ~/.zprezto
	git pull && git submodule update --init --recursive
	cd -
}

# download any youtube or vimeo video to ~/Movies
download-video() {
	cd ~/Movies
	youtube-dl -t "$@"
}

# play jay-z
jayz() {
	osascript <<-EOF
		tell application "iTunes" to play track 1 of playlist "Jay-Z"
	EOF
}

# clone repo and discard git info
clone() {
	local repo_name=${2:-`echo $1 | awk -F/ '{print $5}' | sed 's/.git//'`}

	git clone --depth=1 "$1" "$repo_name"
	rm -rf "$repo_name"/.git
}

# pull down repo for reading
code-read() {
	local pwd=`pwd`
	local target=~/Dropbox/code/read

	cd "$target"
	clone "$@"
	cd "$pwd"
}

mp3-convert() {
	ffmpeg -i "$@" -acodec libmp3lame -ac 2 -ab 128k -vn -y "$@".mp3
}

add-dropbox-remote() {
	local target=~/Dropbox/.gitrepos/${PWD##*/}.git
	if [ -d "$target" ]; then
		  # Control will enter here if $DIRECTORY exists.
		  echo "$target" already exists
	  else
		  git clone --bare . "$target"
		  git remote add dropbox "$target"
		  echo "added dropbox remote"
		  git remote -v
	fi
}



whiteboard () {
	convert $1 -morphology Convolve DoG:15,100,0 -negate -normalize -blur 0x1 -channel RBG -level 60%,91%,0.1 $2
}
