#!/bin/sh

#source $HOME/.zsh/spectrum

ZSH_THEME_DIR_COLOR=$FG[044]
ZSH_THEME_TEXT_COLOR=$FG[250]
ZSH_THEME_RUBY_VERSION_COLOR=$FG[237]
ZSH_THEME_STOPPED_JOBS_COLOR=$FG[136]

ZSH_THEME_GIT_PROMPT_PREFIX=''
ZSH_THEME_GIT_PROMPT_SUFFIX=' '
ZSH_THEME_GIT_PROMPT_COLOR=$FG[244]
ZSH_THEME_GIT_PROMPT_DIRTY="%{$FG[009]%} ●"
ZSH_THEME_GIT_PROMPT_CLEAN="%{$FG[002]%} ●"

function __prompt_stoppedjobs() {
  local num=$(jobs -s | wc -l | sed -e "s/ //g")
  if [[ ! "$num" -eq "0" ]]; then
    printf " ★ $num"
  fi
}

__prompt_ruby_verision ()
{
  if [ -f "$(pwd)/Gemfile" ]; then
    local rbenv_ruby_version=`rbenv version | sed -e 's/ .*//'`
    printf "♦ $rbenv_ruby_version"
  fi
}

PROMPT='%{$ZSH_THEME_DIR_COLOR%}%c %{$ZSH_THEME_GIT_PROMPT_COLOR%}$(git_prompt_info)%{$ZSH_THEME_TEXT_COLOR%}'

RPROMPT='%{$ZSH_THEME_RUBY_VERSION_COLOR%}$(__prompt_ruby_verision)%{$ZSH_THEME_STOPPED_JOBS_COLOR%}$(__prompt_stoppedjobs)'
