#!/bin/sh

set -u
set -e

SESSION_NAME=irc

LAUNCH=false   # prevent unbound error message if LAUNCH isn't set below

tmux attach -t $SESSION_NAME 2>/dev/null && run_status='OK' || LAUNCH=true

if $LAUNCH; then
  tmux new-session -d -s $SESSION_NAME

  tmux rename-window -t $SESSION_NAME:1 'code'
  tmux send-keys -t $SESSION_NAME:1 "irssi" C-m

  tmux select-window -t $SESSION_NAME:1
  tmux attach -t $SESSION_NAME
fi
